### ISSUE TITLE
感觉还没做完？

### ISSUE THREAD

**Issue by dmhai** [woailibain/kiwiho.EFcore.MultiTenant#1]
看介绍说道：
services.AddSqlServerPerSchema<StoreDbContext>("store", "sqlserver_default");
services.AddMySqlPerTable<CustomerDbContext>("customer", "sqlserver_default");//MySQL 还是 sqlserver？

demo跑通了嘛？

**Comment by woailibain** [comment]
> 看介绍说道：
> services.AddSqlServerPerSchema("store", "sqlserver_default");
> services.AddMySqlPerTable("customer", "sqlserver_default");//MySQL 还是 sqlserver？
> 
> demo跑通了嘛？

demo 当然是可以跑通的。后面那个是参数。想用任何名字都可以。

**Comment by woailibain** [comment]
I would like to close this issue that not exactly an issue
